# ===== Appearance Settings =====
[ui]
panel = false # enable/disable panel
fullscreen = false # fullscreen or not on startup
zoom_level = 1.0 # Default zoom factor
compact = true # Minimal margins in dodo
link_boundary_box = false # show link boundary box
hscrollbar = false # show/hide horizontal scrollbar
vscrollbar = false # show/hide vertical scrollbar
auto_hide_hscrollbar = true # autohide horizontal scrollbar
auto_hide_vscrollbar = true # autohide vertical scrollbar
full_file_path_in_panel = false
menubar = false # show/hide menubar
window_title = "{} - dodo" # '{}' will be replaced with the base name of the opened file

# Format is #AARRGGBB (ARGB format)
[colors]
accent = "#FF3daee9"
background = "#00000000"
search_match = "#33FF5000"
search_index = "#55FFFF55"
link_hint_bg = "#8800FF00"
link_hint_fg = "#FF000000"
selection = "#44FF5000"
highlight = "#55FFFF00"

# ===== Rendering Settings =====
[rendering]
dpi = 300.0 # DPI of the rendered PDF file
cache_pages = 5 # Number of pages to keep in RAM
antialiasing_bits = 8 # 4=good, 8=high quality
icc_color_profile = true # whether to use ICC color profile

# ===== Navigation & Behavior =====
[behavior]
remember_last_visited = true   # Helps to go to last visited page of document
page_history = 100 # History for visited pages in the file (only for the session)
confirm_on_quit = true # Ask before quitting dodo
auto_resize = false # Resize the document to fit the window
zoom_factor = 1.25 # Factor by which to zoom in/out
initial_fit = "width" # Fit applied once every file opened; values: "none", "width", "height", "window":
invert_mode = false # Start in invert color mode
synctex_editor_command = "kitty -e nvim +{line} {file}"

# ===== Shortcuts =====
[keybindings]
open_file = "o"
#close_file = ""
link_hint_visit = "f"
link_hint_copy = "Shift+F"

scroll_left = "h"
scroll_down = "j"
scroll_up = "k"
scroll_right = "l"

prev_location = "Ctrl+o"

next_page = "Shift+J"
prev_page = "Shift+K"
first_page = "g,g"
last_page = "Shift+G"

outline = "t"

search = "/"
search_this_page = "?" #TODO
search_next = "n"
search_prev = "Shift+N"

zoom_reset = "0"
zoom_in = "="
zoom_out = "-"

annot_highlight = "Alt+1"
annot_rect = "Alt+2"
annot_select = "Alt+3"

file_properties = "Ctrl+Shift+F"
invert_color = "i"

fullscreen = "F11"
fit_height = "Ctrl+Shift+H"
fit_width = "Ctrl+Shift+W"
fit_window = "Ctrl+Shift+="
auto_resize = "Ctrl+Shift+R"

toggle_menubar = "Ctrl+Shift+M"
toggle_panel = "Ctrl+Shift+B"

rotate_clock = ">"
rotate_anticlock = "<"

cancel_selection = "escape"
yank = "y"
about = "F12"
save = "Ctrl+S"
select_all = "Ctrl+A"
