# ===== Appearance Settings =====
[ui]
panel = true
fullscreen = false
zoom_level = 1.0            # Default zoom factor
compact = true
link_boundary_box = false
hscrollbar = false
vscrollbar = false
auto_hide_hscrollbar = true
auto_hide_vscrollbar = true
full_file_path_in_panel = false
menubar = false

# Format is #AARRGGBB (ARGB format)
[colors]
accent = "#FF3daee9"    # Hex color code for highlights
background = "#00000000"
search_match = "#33FF5000"
search_index = "#55FFFF55"

# ===== Rendering Settings =====
[rendering]
dpi = 300.0
low_dpi = 72.0
cache_pages = 5            # Number of pages to keep in RAM
antialiasing_bits = 8
icc_color_profile = true

# ===== Navigation & Behavior =====
[behavior]
remember_last_visited = true   # Helps to go to last visited page of document
page_history = 100 # History for visited pages in the file (only for the session)
confirm_on_quit = true # Ask before quitting dodo
auto_resize = true # Resize the document to fit the window
zoom_factor = 1.25 # Factor by which to zoom in/out
initial_fit = "window" # Fit applied once every file opened; values: "none", "width", "height", "window":

# ===== Shortcuts =====
[keybindings]
open_file = "o"

scroll_left = "h"
scroll_down = "j"
scroll_up = "k"
scroll_right = "l"

next_page = "Shift+J"
prev_page = "Shift+K"
first_page = "g,g"
last_page = "Shift+G"

search = "/"

zoom_reset = "0"
zoom_in = "="
zoom_out = "-"

annot_highlight = "Alt+1"
file_properties = "Ctrl+Shift+F"
invert_color = "i"

fullscreen = "<F11>"
fit_height = "Ctrl+Shift+H"
fit_width = "Ctrl+Shift+W"
fit_window = "Ctrl+Shift+="
auto_resize = "Ctrl+Shift+R"

toggle_menubar = "Ctrl+Shift+M"
toggle_panel = "Ctrl+Shift+B"
