# ===== Appearance Settings =====
[ui]
# TODO: theme = "dark"              # Options: dark, light, system
panel_shown = true
fullscreen = false
zoom_level = 1.0            # Default zoom factor
compact = true
link_boundary_box = false
hscrollbar = false
vscrollbar = false
full_file_path_in_panel = true

# Format is #AARRGGBB (ARGB format)
[colors]
accent = "#FF3daee9"    # Hex color code for highlights
background = "#00000000"
search_match = "#33FF5000"
search_index = "#55FFFF55"

# ===== Rendering Settings =====
[rendering]
dpi = 300.0
low_dpi = 72.0
cache_pages = 5            # Number of pages to keep in RAM
antialiasing_bits = 8
icc_color_profile = true

# ===== Navigation & Behavior =====
[behavior]
remember_last_visited = true   # Helps to go to last visited page of document
enable_prefetch = true
prefetch_distance = 2       # How many pages ahead/behind to prefetch
page_history = 100 # History for visited pages in the file
confirm_on_quit = true # Ask before quitting dodo

# ===== Shortcuts =====
[keybindings]
open_file = "o"

scroll_left = "h"
scroll_down = "j"
scroll_up = "k"
scroll_right = "l"

next_page = "Shift+j"
prev_page = "Shift+k"
first_page = "g,g"
last_page = "Shift+g"

search = "/"

zoom_reset = "0"
zoom_in = "="
zoom_out = "-"

fullscreen = "<F11>"
annot_highlight = "Alt+1"
file_properties = "Ctrl+Shift+f"
invert_color = "i"

fit_height = "Ctrl+Shift+h"
fit_width = "Ctrl+Shift"w"
